### ISSUE TITLE
run ansible-pull without -o if a group_var, host_var or other file has been updated

### ISSUE THREAD

**Issue by martbhell** [CSCfi/ansible-role-fgci-install#21]
I have a strong suspicion that the ansible-pull-script now with -o does not notice 
if there's been a change to any of the group or host_vars which are wget mirrored in by  ansible-pull-script.sh

Ideas for how to best find out if a file was updated by wget mirror is appreciated.

**Comment by jabl** [comment]
To be honest, I think the -o option is only applicable in very limited and specific circumstances. It's not only host/group_vars, but in principle every time an ansible role accesses some outside resource. We've already had trouble due to this, e.g. Lustre client failed to update when we rebooted a node with a new kernel, and so forth (@mhakala ran into this, he might know better).

Also, we rely on ansible-pull to start and enable services etc. So if for whatever reason the first ansible-pull-script run doesn't do everything, next time nothing happens.

So I think we should get rid of the -o and instead work towards making the ansible roles idempotent as far as possible (always bouncing the slurm daemons was an issue for us, but certainly there are a lot of smaller issues as well).

**Comment by martbhell** [comment]
I'm leaning towards disabling -o as well. All in favor?

**Comment by A1ve5** [comment]
ok, let's do it. No -o

**Comment by martbhell** [comment]
We probably have to add back the "git pull" in ansible-pull-script now that I removed it in https://github.com/CSC-IT-Center-for-Science/ansible-role-fgci-install/commit/320d4c7051854e938b76299e91c35b62cae95238#diff-c68960d63a563cd6186d2379dd6030baL65

**Comment by A1ve5** [comment]
like this? https://github.com/CSC-IT-Center-for-Science/ansible-role-fgci-install/compare/73dfcde41e9c...cd7d253b766e

**Comment by martbhell** [comment]
I think that should do it yes. But I don't know if git pull is necessary (or if ansible-pull takes care of it when it behind the scenes runs ansible with the git module), but at least it worked with it so should be good to have.

**Comment by martbhell** [comment]
I think we can merge this now. The script used to check if {{ pull_install_ip }} was in the git remote.origin.url - but that was something put in place when we moved from git cloning directly from github to the gitmirror.
